In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([[1, 0], [0, 1]])

In [3]:
a

array([[1, 0],
       [0, 1]])

In [4]:
b = np.array([1, 2])

In [5]:
a@b

array([1, 2])

In [6]:
work={'date': ['20201012', '20201013', '20201014', '20201015', '20201016', '20201017', '20201018', '20201019', '20201020', '20201021', '20201022', '20201023', '20201026', '20201027', '20201028', '20201030', '20201029', '20201102', '20201103', '20201104', '20201106', '20201109', '20201110', '20201111', '20201112', '20201113', '20201116', '20201117', '20201118', '20201119', '20201120', '20201123', '20201126', '20201125', '20201127', '20201130', '20201201', '20201202', '20201203', '20201204', '20201208', '20201209', '20201207', '20201210', '20201206', '20201217', '20201211', '20201214', '20201218', '20201221', '20201222', '20201223', '20201215', '20201216', '20201105'], 'hours': [8.0, 7.5, 8.0, 8.5, 5.0, 1.0, 5.0, 8.0, 8.0, 8.0, 6.0, 8.0, 6.0, 8.0, 8.0, 8.0, 8.0, 7.0, 8.0, 8.5, 8.0, 8.0, 8.0, 9.0, 8.0, 8.0, 6.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 7.0, 8.0, 8.0, 8.0, 8.0, 6.0, 8.0, 8.0, 8.0, 7.0, 9.0, 4.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 9.0, 9.0, 8.0]}

In [9]:
pd.DataFrame.from_dict(work).sort_values(by='hours')

        date  hours
5   20201017    1.0
44  20201206    4.0
4   20201016    5.0
6   20201018    5.0
38  20201203    6.0
26  20201116    6.0
12  20201026    6.0
10  20201022    6.0
42  20201207    7.0
17  20201102    7.0
33  20201125    7.0
1   20201013    7.5
39  20201204    8.0
36  20201201    8.0
37  20201202    8.0
32  20201126    8.0
35  20201130    8.0
34  20201127    8.0
0   20201012    8.0
41  20201209    8.0
31  20201123    8.0
45  20201217    8.0
46  20201211    8.0
47  20201214    8.0
48  20201218    8.0
49  20201221    8.0
50  20201222    8.0
51  20201223    8.0
40  20201208    8.0
30  20201120    8.0
27  20201117    8.0
28  20201118    8.0
2   20201014    8.0
7   20201019    8.0
8   20201020    8.0
9   20201021    8.0
11  20201023    8.0
13  20201027    8.0
14  20201028    8.0
29  20201119    8.0
16  20201029    8.0
15  20201030    8.0
20  20201106    8.0
21  20201109    8.0
22  20201110    8.0
24  20201112    8.0
25  20201113    8.0
18  20201103    8.0
54  20201105    8.0
19  20201104    8.5
3   20201015    8.5
43  20201210    9.0
23  20201111    9.0
53  20201216    9.0
52  20201215    9.0